# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "15c8afc4a1e0648dde6da5870549dcb0"
name = "Drapit Virtual Try-On"
application_url = "https://drapit.io/dashboard"
embedded = false

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  compliance_topics = ["customers/data_request"]
  uri = "https://drapit.io/api/webhook/shopify/customers/data_request"

  [[webhooks.subscriptions]]
  compliance_topics = ["customers/redact"]
  uri = "https://drapit.io/api/webhook/shopify/customers/redact"

  [[webhooks.subscriptions]]
  compliance_topics = ["shop/redact"]
  uri = "https://drapit.io/api/webhook/shopify/shop/redact"

  [[webhooks.subscriptions]]
  topics = ["app/uninstalled"]
  uri = "https://drapit.io/api/webhook/shopify/app/uninstalled"

[access_scopes]
scopes = "read_themes,write_themes"

[auth]
redirect_urls = [
  "https://drapit.io/api/auth/callback",
  "https://drapit.io/api/auth/shopify/callback"
]
